<?php

namespace App\Filament\Resources\TurmasResource\Pages;

use App\Filament\Resources\TurmaResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateTurma extends CreateRecord
{
    protected static string $resource = TurmaResource::class;

    public function mount(): void
    {
        if (!auth()->user()->id) {
            $this->redirect('/login');
        }

        if (!auth()->user()->isVerified()) {
            $this->redirect('/admin');
        }

        parent::mount(); // TODO: Change the autogenerated stub
    }

    protected function getRedirectUrl(): string
    {
        return static::getResource()::getUrl('index');
    }

    public function getTitle(): string
    {
        return 'Criar Turma';
    }
}
