<?php

namespace App\Filament\Resources\TurmasResource\Pages;

use App\Filament\Resources\TurmaResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditTurma extends EditRecord
{
    protected static string $resource = TurmaResource::class;
    
        public function getTitle(): string
        {
            return 'Editar Turma';
        }
    
        public function getBreadcrumb(): string
        {
            return 'Editar';
        }

    public function mount(int|string $record): void
    {
        parent::mount($record); // TODO: Change the autogenerated stub

        if (!auth()->user()) {
            $this->redirect('/login');
        }

        if (!auth()->user()->isVerified()) {
            $this->redirect('/admin');
        }
    }

    protected function getFormActions(): array
    {
        return [
            $this->getSaveFormAction()
                ->label('Salvar Alterações'),
    
            $this->getCancelFormAction()
                ->label('Cancelar'),
        ];
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make()
                ->label('Deletar'),
        ];
    }
}
